sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build processor-skip-lines
script: docker-compose run --rm --entrypoint sh -e KBC_PARAMETER_LINES=2 -e KBC_DATADIR=/code/Tests/data processor-skip-lines /code/Tests/run.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
