sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build
  - docker-compose run --rm tests ls -1Rla /code
script: docker-compose run --rm tests
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
